# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 801895f805c9e07806dd1a45140053f8ba788be7384329659d8e242312aa8e37cf60ed02df6e80a7aebd0c84f6385c93d4b489b61da82abbfda4898279714b4a

test:
  secret_key_base: 0b8e83ff32d35130b45e0340a615ba659d6e4ca51586cbab4da916c4a43ee71aca2722ee09780a154e026fbaca03f33ca41396a21f8ed6c442253962e4a62dc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
